### ISSUE TITLE
only can you share data? to try your code?

### ISSUE THREAD

**Issue by Sandy4321** [LogicJake/2020_KDD_Debiasing_TOP13#1]
only can you share data? to try your code?

**Comment by LogicJake** [comment]
https://pan.baidu.com/s/1bf5lpP0yqebXF4yHhHv0Lw 提取码：zf58

It's in readme.

**Comment by Sandy4321** [comment]
great thanks for help
though this page  is in Chinese and also no option to download
can you pls upload to google drive?
![image](https://user-images.githubusercontent.com/11426119/85301998-92c8df80-b476-11ea-9298-9ba03d69c4c5.png)

**Comment by Sandy4321** [comment]
google drive needed pls
![image](https://user-images.githubusercontent.com/11426119/85312574-feb24480-b484-11ea-8c97-13934d1c5042.png)

**Comment by Sandy4321** [comment]
maybe this link is good?
https://www.kaggle.com/hxshine/kdd-2020
