### ISSUE TITLE
is this data good to use

### ISSUE THREAD

**Issue by Sandy4321** [LogicJake/2020_KDD_Debiasing_TOP13#2]
is this data good to use
https://www.kaggle.com/hxshine/kdd-2020

or I need another data link?

**Comment by LogicJake** [comment]
It seems right.

**Comment by Sandy4321** [comment]
I see you are not 100% sure
can you share data really used ?

**Comment by LogicJake** [comment]
https://drive.google.com/drive/folders/1M2mgeovpfAZQnqo6Fn_cbyjQm0bYyXew?usp=sharing

**Comment by Sandy4321** [comment]
great thanks
now I can try your code
![image](https://user-images.githubusercontent.com/11426119/85585184-c722d400-b60d-11ea-8e6f-a425ca952926.png)
