### ISSUE TITLE
排序阶段的lightgbm中没有使用两个深度模型的概率

### ISSUE THREAD

**Issue by SummerRaining** [LogicJake/2020_KDD_Debiasing_TOP13#3]
楼主，我在学习rank_model文件的时候，发现“在特征表中加入深度模型概率“的代码注释掉了。而且在lightgbm输出的特征重要性排序中，也没有深度学习模型的概率。这是说明深度学习输出概率这个特征其实并不重要吗？

**Comment by LogicJake** [comment]
有效的，注释是因为开源前测试代码能不能跑通暂时先注释了，后面忘记修改了。
